'use client';

/**
 * Mock/Dummy Data for Development
 * Replace with real Firestore data when ready
 */

import { Match, Performance } from './cricket-schema';

// Sample Matches Data
export const MOCK_MATCHES: Match[] = [
  {
    id: 'match001',
    date: '2024-03-15',
    year: '2024',
    month: '2024-03',
    opponent: 'Royal Blaze',
    venue: 'Home',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '24 runs',
    bestBatterId: 'p001',
    bestBatterName: 'Rohit Sharma',
    bestBatterRuns: 87,
    bestBatterBalls: 52,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 3,
    bestBowlerRuns: 22,
    createdAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'match002',
    date: '2024-03-20',
    year: '2024',
    month: '2024-03',
    opponent: 'Thunder Warriors',
    venue: 'Away',
    tossWonBy: 'Opponent',
    tossDecision: 'field',
    result: 'lost',
    winMargin: '15 runs',
    bestBatterId: 'p002',
    bestBatterName: 'Virat Kohli',
    bestBatterRuns: 65,
    bestBatterBalls: 48,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 2,
    bestBowlerRuns: 28,
    createdAt: '2024-03-20T10:00:00Z',
  },
  {
    id: 'match003',
    date: '2024-03-25',
    year: '2024',
    month: '2024-03',
    opponent: 'Phoenix Rising',
    venue: 'Neutral',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '8 wickets',
    bestBatterId: 'p001',
    bestBatterName: 'Rohit Sharma',
    bestBatterRuns: 92,
    bestBatterBalls: 58,
    bestBowlerId: 'p007',
    bestBowlerName: 'Kuldeep Yadav',
    bestBowlerWickets: 4,
    bestBowlerRuns: 18,
    createdAt: '2024-03-25T10:00:00Z',
  },
  {
    id: 'match004',
    date: '2024-04-01',
    year: '2024',
    month: '2024-04',
    opponent: 'Night Strikers',
    venue: 'Home',
    tossWonBy: 'Opponent',
    tossDecision: 'bat',
    result: 'no_result',
    winMargin: '',
    bestBatterId: 'p003',
    bestBatterName: 'KL Rahul',
    bestBatterRuns: 54,
    bestBatterBalls: 42,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 1,
    bestBowlerRuns: 25,
    createdAt: '2024-04-01T10:00:00Z',
  },
  {
    id: 'match005',
    date: '2024-04-05',
    year: '2024',
    month: '2024-04',
    opponent: 'Dragon Force',
    venue: 'Away',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '35 runs',
    bestBatterId: 'p004',
    bestBatterName: 'Surya Kumar Yadav',
    bestBatterRuns: 78,
    bestBatterBalls: 50,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 3,
    bestBowlerRuns: 20,
    createdAt: '2024-04-05T10:00:00Z',
  },
  {
    id: 'match006',
    date: '2024-04-12',
    year: '2024',
    month: '2024-04',
    opponent: 'Silver Titans',
    venue: 'Home',
    tossWonBy: 'Us',
    tossDecision: 'field',
    result: 'won',
    winMargin: '6 wickets',
    bestBatterId: 'p002',
    bestBatterName: 'Virat Kohli',
    bestBatterRuns: 71,
    bestBatterBalls: 54,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 4,
    bestBowlerRuns: 15,
    createdAt: '2024-04-12T10:00:00Z',
  },
  {
    id: 'match007',
    date: '2024-05-02',
    year: '2024',
    month: '2024-05',
    opponent: 'Golden Eagles',
    venue: 'Away',
    tossWonBy: 'Opponent',
    tossDecision: 'bat',
    result: 'lost',
    winMargin: '22 runs',
    bestBatterId: 'p001',
    bestBatterName: 'Rohit Sharma',
    bestBatterRuns: 68,
    bestBatterBalls: 55,
    bestBowlerId: 'p007',
    bestBowlerName: 'Kuldeep Yadav',
    bestBowlerWickets: 2,
    bestBowlerRuns: 32,
    createdAt: '2024-05-02T10:00:00Z',
  },
  {
    id: 'match008',
    date: '2024-05-10',
    year: '2024',
    month: '2024-05',
    opponent: 'Crimson Kings',
    venue: 'Neutral',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '12 runs',
    bestBatterId: 'p003',
    bestBatterName: 'KL Rahul',
    bestBatterRuns: 81,
    bestBatterBalls: 61,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 3,
    bestBowlerRuns: 24,
    createdAt: '2024-05-10T10:00:00Z',
  },
  {
    id: 'match009',
    date: '2024-05-18',
    year: '2024',
    month: '2024-05',
    opponent: 'Azure Waves',
    venue: 'Home',
    tossWonBy: 'Opponent',
    tossDecision: 'field',
    result: 'tie',
    winMargin: '',
    bestBatterId: 'p004',
    bestBatterName: 'Surya Kumar Yadav',
    bestBatterRuns: 76,
    bestBatterBalls: 49,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 3,
    bestBowlerRuns: 28,
    createdAt: '2024-05-18T10:00:00Z',
  },
  {
    id: 'match010',
    date: '2024-06-01',
    year: '2024',
    month: '2024-06',
    opponent: 'Sapphire Squad',
    venue: 'Away',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '18 runs',
    bestBatterId: 'p002',
    bestBatterName: 'Virat Kohli',
    bestBatterRuns: 89,
    bestBatterBalls: 63,
    bestBowlerId: 'p007',
    bestBowlerName: 'Kuldeep Yadav',
    bestBowlerWickets: 4,
    bestBowlerRuns: 21,
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'match011',
    date: '2024-06-08',
    year: '2024',
    month: '2024-06',
    opponent: 'Jade Jaguars',
    venue: 'Home',
    tossWonBy: 'Opponent',
    tossDecision: 'bat',
    result: 'lost',
    winMargin: '9 wickets',
    bestBatterId: 'p001',
    bestBatterName: 'Rohit Sharma',
    bestBatterRuns: 44,
    bestBatterBalls: 38,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 2,
    bestBowlerRuns: 31,
    createdAt: '2024-06-08T10:00:00Z',
  },
  {
    id: 'match012',
    date: '2024-06-15',
    year: '2024',
    month: '2024-06',
    opponent: 'Emerald Legends',
    venue: 'Neutral',
    tossWonBy: 'Us',
    tossDecision: 'field',
    result: 'won',
    winMargin: '5 wickets',
    bestBatterId: 'p003',
    bestBatterName: 'KL Rahul',
    bestBatterRuns: 73,
    bestBatterBalls: 56,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 5,
    bestBowlerRuns: 19,
    createdAt: '2024-06-15T10:00:00Z',
  },
  {
    id: 'match013',
    date: '2024-07-05',
    year: '2024',
    month: '2024-07',
    opponent: 'Indigo Strikers',
    venue: 'Away',
    tossWonBy: 'Opponent',
    tossDecision: 'field',
    result: 'won',
    winMargin: '7 wickets',
    bestBatterId: 'p004',
    bestBatterName: 'Surya Kumar Yadav',
    bestBatterRuns: 95,
    bestBatterBalls: 62,
    bestBowlerId: 'p007',
    bestBowlerName: 'Kuldeep Yadav',
    bestBowlerWickets: 3,
    bestBowlerRuns: 26,
    createdAt: '2024-07-05T10:00:00Z',
  },
  {
    id: 'match014',
    date: '2024-07-12',
    year: '2024',
    month: '2024-07',
    opponent: 'Violet Vikings',
    venue: 'Home',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '28 runs',
    bestBatterId: 'p001',
    bestBatterName: 'Rohit Sharma',
    bestBatterRuns: 84,
    bestBatterBalls: 51,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 4,
    bestBowlerRuns: 23,
    createdAt: '2024-07-12T10:00:00Z',
  },
  {
    id: 'match015',
    date: '2024-07-20',
    year: '2024',
    month: '2024-07',
    opponent: 'Maroon Marauders',
    venue: 'Neutral',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'lost',
    winMargin: '4 wickets',
    bestBatterId: 'p002',
    bestBatterName: 'Virat Kohli',
    bestBatterRuns: 62,
    bestBatterBalls: 45,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 2,
    bestBowlerRuns: 36,
    createdAt: '2024-07-20T10:00:00Z',
  },
  {
    id: 'match016',
    date: '2023-10-15',
    year: '2023',
    month: '2023-10',
    opponent: 'Bronze Bruisers',
    venue: 'Home',
    tossWonBy: 'Opponent',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '31 runs',
    bestBatterId: 'p003',
    bestBatterName: 'KL Rahul',
    bestBatterRuns: 79,
    bestBatterBalls: 57,
    bestBowlerId: 'p007',
    bestBowlerName: 'Kuldeep Yadav',
    bestBowlerWickets: 4,
    bestBowlerRuns: 20,
    createdAt: '2023-10-15T10:00:00Z',
  },
  {
    id: 'match017',
    date: '2023-10-22',
    year: '2023',
    month: '2023-10',
    opponent: 'Chrome Chargers',
    venue: 'Away',
    tossWonBy: 'Us',
    tossDecision: 'field',
    result: 'lost',
    winMargin: '11 runs',
    bestBatterId: 'p004',
    bestBatterName: 'Surya Kumar Yadav',
    bestBatterRuns: 71,
    bestBatterBalls: 52,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 3,
    bestBowlerRuns: 29,
    createdAt: '2023-10-22T10:00:00Z',
  },
  {
    id: 'match018',
    date: '2023-11-05',
    year: '2023',
    month: '2023-11',
    opponent: 'Copper Crusaders',
    venue: 'Neutral',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '19 runs',
    bestBatterId: 'p001',
    bestBatterName: 'Rohit Sharma',
    bestBatterRuns: 88,
    bestBatterBalls: 60,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 3,
    bestBowlerRuns: 27,
    createdAt: '2023-11-05T10:00:00Z',
  },
  {
    id: 'match019',
    date: '2023-11-18',
    year: '2023',
    month: '2023-11',
    opponent: 'Iron Invaders',
    venue: 'Home',
    tossWonBy: 'Opponent',
    tossDecision: 'field',
    result: 'no_result',
    winMargin: '',
    bestBatterId: 'p002',
    bestBatterName: 'Virat Kohli',
    bestBatterRuns: 56,
    bestBatterBalls: 41,
    bestBowlerId: 'p007',
    bestBowlerName: 'Kuldeep Yadav',
    bestBowlerWickets: 2,
    bestBowlerRuns: 33,
    createdAt: '2023-11-18T10:00:00Z',
  },
  {
    id: 'match020',
    date: '2025-01-10',
    year: '2025',
    month: '2025-01',
    opponent: 'Titanium Titans',
    venue: 'Away',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '26 runs',
    bestBatterId: 'p003',
    bestBatterName: 'KL Rahul',
    bestBatterRuns: 82,
    bestBatterBalls: 59,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 4,
    bestBowlerRuns: 22,
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'match021',
    date: '2025-01-18',
    year: '2025',
    month: '2025-01',
    opponent: 'Platinum Panthers',
    venue: 'Home',
    tossWonBy: 'Opponent',
    tossDecision: 'bat',
    result: 'lost',
    winMargin: '16 runs',
    bestBatterId: 'p004',
    bestBatterName: 'Surya Kumar Yadav',
    bestBatterRuns: 69,
    bestBatterBalls: 51,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 3,
    bestBowlerRuns: 30,
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 'match022',
    date: '2025-02-02',
    year: '2025',
    month: '2025-02',
    opponent: 'Gold Gazelles',
    venue: 'Neutral',
    tossWonBy: 'Us',
    tossDecision: 'field',
    result: 'won',
    winMargin: '3 wickets',
    bestBatterId: 'p001',
    bestBatterName: 'Rohit Sharma',
    bestBatterRuns: 76,
    bestBatterBalls: 54,
    bestBowlerId: 'p007',
    bestBowlerName: 'Kuldeep Yadav',
    bestBowlerWickets: 4,
    bestBowlerRuns: 25,
    createdAt: '2025-02-02T10:00:00Z',
  },
  {
    id: 'match023',
    date: '2025-02-14',
    year: '2025',
    month: '2025-02',
    opponent: 'Silver Stallions',
    venue: 'Away',
    tossWonBy: 'Opponent',
    tossDecision: 'field',
    result: 'tie',
    winMargin: '',
    bestBatterId: 'p002',
    bestBatterName: 'Virat Kohli',
    bestBatterRuns: 84,
    bestBatterBalls: 58,
    bestBowlerId: 'p006',
    bestBowlerName: 'Mohammed Siraj',
    bestBowlerWickets: 3,
    bestBowlerRuns: 28,
    createdAt: '2025-02-14T10:00:00Z',
  },
  {
    id: 'match024',
    date: '2025-02-25',
    year: '2025',
    month: '2025-02',
    opponent: 'Pearl Panthers',
    venue: 'Home',
    tossWonBy: 'Us',
    tossDecision: 'bat',
    result: 'won',
    winMargin: '39 runs',
    bestBatterId: 'p003',
    bestBatterName: 'KL Rahul',
    bestBatterRuns: 91,
    bestBatterBalls: 65,
    bestBowlerId: 'p005',
    bestBowlerName: 'Jasprit Bumrah',
    bestBowlerWickets: 4,
    bestBowlerRuns: 18,
    createdAt: '2025-02-25T10:00:00Z',
  },
];

// Sample Performances Data
export const MOCK_PERFORMANCES: Performance[] = [
  // Match 1 - Royal Blaze
  { id: 'match001_p001', matchId: 'match001', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-03-15', year: '2024', month: '2024-03', opponent: 'Royal Blaze', batting: { didBat: true, innings: 1, runs: 56, balls: 45, fours: 6, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 124.4 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-03-15T10:00:00Z' },
  { id: 'match001_p002', matchId: 'match001', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-03-15', year: '2024', month: '2024-03', opponent: 'Royal Blaze', batting: { didBat: true, innings: 1, runs: 72, balls: 56, fours: 8, sixes: 1, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 128.6 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-03-15T10:00:00Z' },
  { id: 'match001_p005', matchId: 'match001', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2024-03-15', year: '2024', month: '2024-03', opponent: 'Royal Blaze', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 12, wickets: 3, maidens: 1, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 3.0 }, createdAt: '2024-03-15T10:00:00Z' },

  // Match 2 - Titan Force
  { id: 'match002_p002', matchId: 'match002', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-03-18', year: '2024', month: '2024-03', opponent: 'Titan Force', batting: { didBat: true, innings: 1, runs: 81, balls: 59, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 137.3 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-03-18T10:00:00Z' },
  { id: 'match002_p001', matchId: 'match002', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-03-18', year: '2024', month: '2024-03', opponent: 'Titan Force', batting: { didBat: true, innings: 1, runs: 74, balls: 57, fours: 8, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 129.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-03-18T10:00:00Z' },
  { id: 'match002_p006', matchId: 'match002', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2024-03-18', year: '2024', month: '2024-03', opponent: 'Titan Force', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 18, wickets: 2, maidens: 1, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 4.5 }, createdAt: '2024-03-18T10:00:00Z' },

  // Match 3 - Phoenix Rising
  { id: 'match003_p001', matchId: 'match003', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-03-25', year: '2024', month: '2024-03', opponent: 'Phoenix Rising', batting: { didBat: true, innings: 1, runs: 63, balls: 50, fours: 7, sixes: 1, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 126.0 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-03-25T10:00:00Z' },
  { id: 'match003_p002', matchId: 'match003', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-03-25', year: '2024', month: '2024-03', opponent: 'Phoenix Rising', batting: { didBat: true, innings: 1, runs: 58, balls: 44, fours: 6, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 131.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-03-25T10:00:00Z' },
  { id: 'match003_p007', matchId: 'match003', playerId: 'p007', playerName: 'Kuldeep Yadav', playerRole: 'bowler', date: '2024-03-25', year: '2024', month: '2024-03', opponent: 'Phoenix Rising', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 18, wickets: 4, maidens: 1, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 4.5 }, createdAt: '2024-03-25T10:00:00Z' },

  // Match 4 - Emerald Elites
  { id: 'match004_p003', matchId: 'match004', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2024-04-02', year: '2024', month: '2024-04', opponent: 'Emerald Elites', batting: { didBat: true, innings: 1, runs: 67, balls: 51, fours: 7, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 131.4 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-04-02T10:00:00Z' },
  { id: 'match004_p001', matchId: 'match004', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-04-02', year: '2024', month: '2024-04', opponent: 'Emerald Elites', batting: { didBat: true, innings: 1, runs: 45, balls: 37, fours: 5, sixes: 0, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 121.6 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-04-02T10:00:00Z' },
  { id: 'match004_p005', matchId: 'match004', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2024-04-02', year: '2024', month: '2024-04', opponent: 'Emerald Elites', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 24, wickets: 2, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 6.0 }, createdAt: '2024-04-02T10:00:00Z' },

  // Match 5 - Sapphire Saints
  { id: 'match005_p004', matchId: 'match005', playerId: 'p004', playerName: 'Surya Kumar Yadav', playerRole: 'batsman', date: '2024-04-08', year: '2024', month: '2024-04', opponent: 'Sapphire Saints', batting: { didBat: true, innings: 1, runs: 92, balls: 58, fours: 10, sixes: 3, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 158.6 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-04-08T10:00:00Z' },
  { id: 'match005_p002', matchId: 'match005', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-04-08', year: '2024', month: '2024-04', opponent: 'Sapphire Saints', batting: { didBat: true, innings: 1, runs: 68, balls: 52, fours: 7, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 130.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-04-08T10:00:00Z' },
  { id: 'match005_p006', matchId: 'match005', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2024-04-08', year: '2024', month: '2024-04', opponent: 'Sapphire Saints', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 28, wickets: 3, maidens: 0, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 7.0 }, createdAt: '2024-04-08T10:00:00Z' },

  // Match 6 - Silver Titans
  { id: 'match006_p001', matchId: 'match006', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-04-12', year: '2024', month: '2024-04', opponent: 'Silver Titans', batting: { didBat: true, innings: 1, runs: 65, balls: 48, fours: 7, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 135.4 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-04-12T10:00:00Z' },
  { id: 'match006_p002', matchId: 'match006', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-04-12', year: '2024', month: '2024-04', opponent: 'Silver Titans', batting: { didBat: true, innings: 1, runs: 71, balls: 54, fours: 8, sixes: 2, dismissed: false, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 131.5 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-04-12T10:00:00Z' },
  { id: 'match006_p005', matchId: 'match006', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2024-04-12', year: '2024', month: '2024-04', opponent: 'Silver Titans', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 15, wickets: 4, maidens: 2, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 3.75 }, createdAt: '2024-04-12T10:00:00Z' },

  // Match 7 - Golden Eagles
  { id: 'match007_p001', matchId: 'match007', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-05-02', year: '2024', month: '2024-05', opponent: 'Golden Eagles', batting: { didBat: true, innings: 1, runs: 68, balls: 55, fours: 7, sixes: 1, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 123.6 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-05-02T10:00:00Z' },
  { id: 'match007_p002', matchId: 'match007', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-05-02', year: '2024', month: '2024-05', opponent: 'Golden Eagles', batting: { didBat: true, innings: 1, runs: 52, balls: 46, fours: 5, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 113.0 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-05-02T10:00:00Z' },
  { id: 'match007_p007', matchId: 'match007', playerId: 'p007', playerName: 'Kuldeep Yadav', playerRole: 'bowler', date: '2024-05-02', year: '2024', month: '2024-05', opponent: 'Golden Eagles', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 32, wickets: 2, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 8.0 }, createdAt: '2024-05-02T10:00:00Z' },

  // Match 8 - Crimson Kings
  { id: 'match008_p001', matchId: 'match008', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-05-10', year: '2024', month: '2024-05', opponent: 'Crimson Kings', batting: { didBat: true, innings: 1, runs: 72, balls: 56, fours: 8, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 128.6 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-05-10T10:00:00Z' },
  { id: 'match008_p003', matchId: 'match008', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2024-05-10', year: '2024', month: '2024-05', opponent: 'Crimson Kings', batting: { didBat: true, innings: 1, runs: 81, balls: 61, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 132.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-05-10T10:00:00Z' },
  { id: 'match008_p006', matchId: 'match008', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2024-05-10', year: '2024', month: '2024-05', opponent: 'Crimson Kings', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 24, wickets: 3, maidens: 1, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 6.0 }, createdAt: '2024-05-10T10:00:00Z' },

  // Match 9 - Azure Waves
  { id: 'match009_p002', matchId: 'match009', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-05-18', year: '2024', month: '2024-05', opponent: 'Azure Waves', batting: { didBat: true, innings: 1, runs: 61, balls: 49, fours: 7, sixes: 1, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 124.5 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-05-18T10:00:00Z' },
  { id: 'match009_p004', matchId: 'match009', playerId: 'p004', playerName: 'Surya Kumar Yadav', playerRole: 'batsman', date: '2024-05-18', year: '2024', month: '2024-05', opponent: 'Azure Waves', batting: { didBat: true, innings: 1, runs: 76, balls: 49, fours: 8, sixes: 3, dismissed: false, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 155.1 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-05-18T10:00:00Z' },
  { id: 'match009_p005', matchId: 'match009', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2024-05-18', year: '2024', month: '2024-05', opponent: 'Azure Waves', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 28, wickets: 3, maidens: 0, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 7.0 }, createdAt: '2024-05-18T10:00:00Z' },

  // Match 10 - Sapphire Squad
  { id: 'match010_p001', matchId: 'match010', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-06-01', year: '2024', month: '2024-06', opponent: 'Sapphire Squad', batting: { didBat: true, innings: 1, runs: 79, balls: 58, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 136.2 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-06-01T10:00:00Z' },
  { id: 'match010_p002', matchId: 'match010', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-06-01', year: '2024', month: '2024-06', opponent: 'Sapphire Squad', batting: { didBat: true, innings: 1, runs: 89, balls: 63, fours: 10, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 141.3 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-06-01T10:00:00Z' },
  { id: 'match010_p007', matchId: 'match010', playerId: 'p007', playerName: 'Kuldeep Yadav', playerRole: 'bowler', date: '2024-06-01', year: '2024', month: '2024-06', opponent: 'Sapphire Squad', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 21, wickets: 4, maidens: 1, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 5.25 }, createdAt: '2024-06-01T10:00:00Z' },

  // Match 11 - Jade Jaguars
  { id: 'match011_p002', matchId: 'match011', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-06-08', year: '2024', month: '2024-06', opponent: 'Jade Jaguars', batting: { didBat: true, innings: 1, runs: 58, balls: 51, fours: 6, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 113.7 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-06-08T10:00:00Z' },
  { id: 'match011_p004', matchId: 'match011', playerId: 'p004', playerName: 'Surya Kumar Yadav', playerRole: 'batsman', date: '2024-06-08', year: '2024', month: '2024-06', opponent: 'Jade Jaguars', batting: { didBat: true, innings: 1, runs: 42, balls: 38, fours: 4, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 110.5 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-06-08T10:00:00Z' },
  { id: 'match011_p006', matchId: 'match011', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2024-06-08', year: '2024', month: '2024-06', opponent: 'Jade Jaguars', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 31, wickets: 2, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 7.75 }, createdAt: '2024-06-08T10:00:00Z' },

  // Match 12 - Emerald Legends
  { id: 'match012_p001', matchId: 'match012', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-06-15', year: '2024', month: '2024-06', opponent: 'Emerald Legends', batting: { didBat: true, innings: 1, runs: 66, balls: 52, fours: 7, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 126.9 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-06-15T10:00:00Z' },
  { id: 'match012_p003', matchId: 'match012', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2024-06-15', year: '2024', month: '2024-06', opponent: 'Emerald Legends', batting: { didBat: true, innings: 1, runs: 73, balls: 56, fours: 8, sixes: 2, dismissed: false, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 130.4 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-06-15T10:00:00Z' },
  { id: 'match012_p005', matchId: 'match012', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2024-06-15', year: '2024', month: '2024-06', opponent: 'Emerald Legends', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 19, wickets: 5, maidens: 1, isThreeFer: false, isFourFer: false, isFiveFer: true, economy: 4.75 }, createdAt: '2024-06-15T10:00:00Z' },

  // Virat Kohli performances
  {
    id: 'match002_p002',
    matchId: 'match002',
    playerId: 'p002',
    playerName: 'Virat Kohli',
    playerRole: 'batsman',
    date: '2024-03-20',
    year: '2024',
    month: '2024-03',
    opponent: 'Thunder Warriors',
    batting: {
      didBat: true,
      innings: 1,
      runs: 65,
      balls: 48,
      fours: 7,
      sixes: 1,
      dismissed: true,
      isDuck: false,
      isThirty: false,
      isFifty: true,
      isHundred: false,
      strikeRate: 135.4,
    },
    bowling: {
      didBowl: false,
      innings: 0,
      overs: 0,
      balls: 0,
      runs: 0,
      wickets: 0,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 0,
    },
    createdAt: '2024-03-20T10:00:00Z',
  },
  {
    id: 'match001_p002',
    matchId: 'match001',
    playerId: 'p002',
    playerName: 'Virat Kohli',
    playerRole: 'batsman',
    date: '2024-03-15',
    year: '2024',
    month: '2024-03',
    opponent: 'Royal Blaze',
    batting: {
      didBat: true,
      innings: 1,
      runs: 78,
      balls: 55,
      fours: 9,
      sixes: 2,
      dismissed: true,
      isDuck: false,
      isThirty: false,
      isFifty: true,
      isHundred: false,
      strikeRate: 141.8,
    },
    bowling: {
      didBowl: false,
      innings: 0,
      overs: 0,
      balls: 0,
      runs: 0,
      wickets: 0,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 0,
    },
    createdAt: '2024-03-15T10:00:00Z',
  },
  // KL Rahul performances
  {
    id: 'match004_p003',
    matchId: 'match004',
    playerId: 'p003',
    playerName: 'KL Rahul',
    playerRole: 'batsman',
    date: '2024-04-01',
    year: '2024',
    month: '2024-04',
    opponent: 'Night Strikers',
    batting: {
      didBat: true,
      innings: 1,
      runs: 54,
      balls: 42,
      fours: 5,
      sixes: 1,
      dismissed: true,
      isDuck: false,
      isThirty: true,
      isFifty: false,
      isHundred: false,
      strikeRate: 128.6,
    },
    bowling: {
      didBowl: false,
      innings: 0,
      overs: 0,
      balls: 0,
      runs: 0,
      wickets: 0,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 0,
    },
    createdAt: '2024-04-01T10:00:00Z',
  },
  // Surya Kumar Yadav performances
  {
    id: 'match005_p004',
    matchId: 'match005',
    playerId: 'p004',
    playerName: 'Surya Kumar Yadav',
    playerRole: 'batsman',
    date: '2024-04-05',
    year: '2024',
    month: '2024-04',
    opponent: 'Dragon Force',
    batting: {
      didBat: true,
      innings: 1,
      runs: 78,
      balls: 50,
      fours: 8,
      sixes: 3,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: true,
      isHundred: false,
      strikeRate: 156.0,
    },
    bowling: {
      didBowl: false,
      innings: 0,
      overs: 0,
      balls: 0,
      runs: 0,
      wickets: 0,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 0,
    },
    createdAt: '2024-04-05T10:00:00Z',
  },
  // Jasprit Bumrah bowling performances
  {
    id: 'match001_p005',
    matchId: 'match001',
    playerId: 'p005',
    playerName: 'Jasprit Bumrah',
    playerRole: 'bowler',
    date: '2024-03-15',
    year: '2024',
    month: '2024-03',
    opponent: 'Royal Blaze',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 4,
      balls: 24,
      runs: 22,
      wickets: 3,
      maidens: 1,
      isThreeFer: true,
      isFourFer: false,
      isFiveFer: false,
      economy: 5.5,
    },
    createdAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'match004_p005',
    matchId: 'match004',
    playerId: 'p005',
    playerName: 'Jasprit Bumrah',
    playerRole: 'bowler',
    date: '2024-04-01',
    year: '2024',
    month: '2024-04',
    opponent: 'Night Strikers',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 3.2,
      balls: 20,
      runs: 25,
      wickets: 1,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 7.5,
    },
    createdAt: '2024-04-01T10:00:00Z',
  },
  // Mohammed Siraj bowling performances
  {
    id: 'match002_p006',
    matchId: 'match002',
    playerId: 'p006',
    playerName: 'Mohammed Siraj',
    playerRole: 'bowler',
    date: '2024-03-20',
    year: '2024',
    month: '2024-03',
    opponent: 'Thunder Warriors',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 4,
      balls: 24,
      runs: 28,
      wickets: 2,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 7.0,
    },
    createdAt: '2024-03-20T10:00:00Z',
  },
  {
    id: 'match005_p006',
    matchId: 'match005',
    playerId: 'p006',
    playerName: 'Mohammed Siraj',
    playerRole: 'bowler',
    date: '2024-04-05',
    year: '2024',
    month: '2024-04',
    opponent: 'Dragon Force',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 4,
      balls: 24,
      runs: 20,
      wickets: 3,
      maidens: 1,
      isThreeFer: true,
      isFourFer: false,
      isFiveFer: false,
      economy: 5.0,
    },
    createdAt: '2024-04-05T10:00:00Z',
  },
  // Kuldeep Yadav bowling performances
  {
    id: 'match003_p007',
    matchId: 'match003',
    playerId: 'p007',
    playerName: 'Kuldeep Yadav',
    playerRole: 'bowler',
    date: '2024-03-25',
    year: '2024',
    month: '2024-03',
    opponent: 'Phoenix Rising',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 4,
      balls: 24,
      runs: 18,
      wickets: 4,
      maidens: 1,
      isThreeFer: false,
      isFourFer: true,
      isFiveFer: false,
      economy: 4.5,
    },
    createdAt: '2024-03-25T10:00:00Z',
  },
  // Match 6 - Silver Titans
  {
    id: 'match006_p002',
    matchId: 'match006',
    playerId: 'p002',
    playerName: 'Virat Kohli',
    playerRole: 'batsman',
    date: '2024-04-12',
    year: '2024',
    month: '2024-04',
    opponent: 'Silver Titans',
    batting: {
      didBat: true,
      innings: 1,
      runs: 71,
      balls: 54,
      fours: 8,
      sixes: 2,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: true,
      isHundred: false,
      strikeRate: 131.5,
    },
    bowling: {
      didBowl: false,
      innings: 0,
      overs: 0,
      balls: 0,
      runs: 0,
      wickets: 0,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 0,
    },
    createdAt: '2024-04-12T10:00:00Z',
  },
  {
    id: 'match006_p005',
    matchId: 'match006',
    playerId: 'p005',
    playerName: 'Jasprit Bumrah',
    playerRole: 'bowler',
    date: '2024-04-12',
    year: '2024',
    month: '2024-04',
    opponent: 'Silver Titans',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 4,
      balls: 24,
      runs: 15,
      wickets: 4,
      maidens: 2,
      isThreeFer: false,
      isFourFer: true,
      isFiveFer: false,
      economy: 3.75,
    },
    createdAt: '2024-04-12T10:00:00Z',
  },
  // Match 8 - Crimson Kings
  {
    id: 'match008_p003',
    matchId: 'match008',
    playerId: 'p003',
    playerName: 'KL Rahul',
    playerRole: 'batsman',
    date: '2024-05-10',
    year: '2024',
    month: '2024-05',
    opponent: 'Crimson Kings',
    batting: {
      didBat: true,
      innings: 1,
      runs: 81,
      balls: 61,
      fours: 9,
      sixes: 2,
      dismissed: true,
      isDuck: false,
      isThirty: false,
      isFifty: true,
      isHundred: false,
      strikeRate: 132.8,
    },
    bowling: {
      didBowl: false,
      innings: 0,
      overs: 0,
      balls: 0,
      runs: 0,
      wickets: 0,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 0,
    },
    createdAt: '2024-05-10T10:00:00Z',
  },
  {
    id: 'match008_p006',
    matchId: 'match008',
    playerId: 'p006',
    playerName: 'Mohammed Siraj',
    playerRole: 'bowler',
    date: '2024-05-10',
    year: '2024',
    month: '2024-05',
    opponent: 'Crimson Kings',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 4,
      balls: 24,
      runs: 24,
      wickets: 3,
      maidens: 1,
      isThreeFer: true,
      isFourFer: false,
      isFiveFer: false,
      economy: 6.0,
    },
    createdAt: '2024-05-10T10:00:00Z',
  },
  // Match 10 - Sapphire Squad
  {
    id: 'match010_p002',
    matchId: 'match010',
    playerId: 'p002',
    playerName: 'Virat Kohli',
    playerRole: 'batsman',
    date: '2024-06-01',
    year: '2024',
    month: '2024-06',
    opponent: 'Sapphire Squad',
    batting: {
      didBat: true,
      innings: 1,
      runs: 89,
      balls: 63,
      fours: 10,
      sixes: 2,
      dismissed: true,
      isDuck: false,
      isThirty: false,
      isFifty: true,
      isHundred: false,
      strikeRate: 141.3,
    },
    bowling: {
      didBowl: false,
      innings: 0,
      overs: 0,
      balls: 0,
      runs: 0,
      wickets: 0,
      maidens: 0,
      isThreeFer: false,
      isFourFer: false,
      isFiveFer: false,
      economy: 0,
    },
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'match010_p007',
    matchId: 'match010',
    playerId: 'p007',
    playerName: 'Kuldeep Yadav',
    playerRole: 'bowler',
    date: '2024-06-01',
    year: '2024',
    month: '2024-06',
    opponent: 'Sapphire Squad',
    batting: {
      didBat: false,
      innings: 0,
      runs: 0,
      balls: 0,
      fours: 0,
      sixes: 0,
      dismissed: false,
      isDuck: false,
      isThirty: false,
      isFifty: false,
      isHundred: false,
      strikeRate: 0,
    },
    bowling: {
      didBowl: true,
      innings: 1,
      overs: 4,
      balls: 24,
      runs: 21,
      wickets: 4,
      maidens: 1,
      isThreeFer: false,
      isFourFer: true,
      isFiveFer: false,
      economy: 5.25,
    },
    createdAt: '2024-06-01T10:00:00Z',
  },
  // Match 13 - Indigo Strikers
  { id: 'match013_p003', matchId: 'match013', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2024-07-05', year: '2024', month: '2024-07', opponent: 'Indigo Strikers', batting: { didBat: true, innings: 1, runs: 87, balls: 60, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 145.0 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-07-05T10:00:00Z' },
  { id: 'match013_p004', matchId: 'match013', playerId: 'p004', playerName: 'Surya Kumar Yadav', playerRole: 'batsman', date: '2024-07-05', year: '2024', month: '2024-07', opponent: 'Indigo Strikers', batting: { didBat: true, innings: 1, runs: 95, balls: 62, fours: 11, sixes: 3, dismissed: false, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 153.2 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-07-05T10:00:00Z' },
  { id: 'match013_p007', matchId: 'match013', playerId: 'p007', playerName: 'Kuldeep Yadav', playerRole: 'bowler', date: '2024-07-05', year: '2024', month: '2024-07', opponent: 'Indigo Strikers', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 26, wickets: 3, maidens: 0, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 6.5 }, createdAt: '2024-07-05T10:00:00Z' },

  // Match 14 - Violet Vikings
  { id: 'match014_p001', matchId: 'match014', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-07-12', year: '2024', month: '2024-07', opponent: 'Violet Vikings', batting: { didBat: true, innings: 1, runs: 84, balls: 51, fours: 10, sixes: 3, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 164.7 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-07-12T10:00:00Z' },
  { id: 'match014_p003', matchId: 'match014', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2024-07-12', year: '2024', month: '2024-07', opponent: 'Violet Vikings', batting: { didBat: true, innings: 1, runs: 69, balls: 55, fours: 7, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 125.5 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-07-12T10:00:00Z' },
  { id: 'match014_p006', matchId: 'match014', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2024-07-12', year: '2024', month: '2024-07', opponent: 'Violet Vikings', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 23, wickets: 4, maidens: 1, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 5.75 }, createdAt: '2024-07-12T10:00:00Z' },

  // Match 15 - Maroon Marauders
  { id: 'match015_p001', matchId: 'match015', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2024-07-20', year: '2024', month: '2024-07', opponent: 'Maroon Marauders', batting: { didBat: true, innings: 1, runs: 57, balls: 48, fours: 6, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 118.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-07-20T10:00:00Z' },
  { id: 'match015_p002', matchId: 'match015', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2024-07-20', year: '2024', month: '2024-07', opponent: 'Maroon Marauders', batting: { didBat: true, innings: 1, runs: 62, balls: 45, fours: 7, sixes: 1, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 137.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2024-07-20T10:00:00Z' },
  { id: 'match015_p005', matchId: 'match015', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2024-07-20', year: '2024', month: '2024-07', opponent: 'Maroon Marauders', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 36, wickets: 2, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 9.0 }, createdAt: '2024-07-20T10:00:00Z' },

  // Match 16 - Bronze Bruisers
  { id: 'match016_p001', matchId: 'match016', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2023-10-15', year: '2023', month: '2023-10', opponent: 'Bronze Bruisers', batting: { didBat: true, innings: 1, runs: 74, balls: 56, fours: 8, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 132.1 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-10-15T10:00:00Z' },
  { id: 'match016_p003', matchId: 'match016', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2023-10-15', year: '2023', month: '2023-10', opponent: 'Bronze Bruisers', batting: { didBat: true, innings: 1, runs: 79, balls: 57, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 138.6 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-10-15T10:00:00Z' },
  { id: 'match016_p007', matchId: 'match016', playerId: 'p007', playerName: 'Kuldeep Yadav', playerRole: 'bowler', date: '2023-10-15', year: '2023', month: '2023-10', opponent: 'Bronze Bruisers', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 20, wickets: 4, maidens: 1, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 5.0 }, createdAt: '2023-10-15T10:00:00Z' },

  // Match 17 - Chrome Chargers
  { id: 'match017_p002', matchId: 'match017', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2023-10-22', year: '2023', month: '2023-10', opponent: 'Chrome Chargers', batting: { didBat: true, innings: 1, runs: 64, balls: 50, fours: 7, sixes: 1, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 128.0 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-10-22T10:00:00Z' },
  { id: 'match017_p004', matchId: 'match017', playerId: 'p004', playerName: 'Surya Kumar Yadav', playerRole: 'batsman', date: '2023-10-22', year: '2023', month: '2023-10', opponent: 'Chrome Chargers', batting: { didBat: true, innings: 1, runs: 71, balls: 52, fours: 8, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 136.5 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-10-22T10:00:00Z' },
  { id: 'match017_p006', matchId: 'match017', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2023-10-22', year: '2023', month: '2023-10', opponent: 'Chrome Chargers', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 29, wickets: 3, maidens: 0, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 7.25 }, createdAt: '2023-10-22T10:00:00Z' },

  // Match 18 - Copper Crusaders
  { id: 'match018_p001', matchId: 'match018', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2023-11-05', year: '2023', month: '2023-11', opponent: 'Copper Crusaders', batting: { didBat: true, innings: 1, runs: 88, balls: 60, fours: 10, sixes: 3, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 146.7 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-11-05T10:00:00Z' },
  { id: 'match018_p002', matchId: 'match018', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2023-11-05', year: '2023', month: '2023-11', opponent: 'Copper Crusaders', batting: { didBat: true, innings: 1, runs: 75, balls: 56, fours: 8, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 133.9 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-11-05T10:00:00Z' },
  { id: 'match018_p005', matchId: 'match018', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2023-11-05', year: '2023', month: '2023-11', opponent: 'Copper Crusaders', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 27, wickets: 3, maidens: 1, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 6.75 }, createdAt: '2023-11-05T10:00:00Z' },

  // Match 19 - Iron Invaders
  { id: 'match019_p003', matchId: 'match019', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2023-11-18', year: '2023', month: '2023-11', opponent: 'Iron Invaders', batting: { didBat: true, innings: 1, runs: 48, balls: 41, fours: 5, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 117.1 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-11-18T10:00:00Z' },
  { id: 'match019_p002', matchId: 'match019', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2023-11-18', year: '2023', month: '2023-11', opponent: 'Iron Invaders', batting: { didBat: true, innings: 1, runs: 56, balls: 41, fours: 6, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 136.6 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2023-11-18T10:00:00Z' },
  { id: 'match019_p007', matchId: 'match019', playerId: 'p007', playerName: 'Kuldeep Yadav', playerRole: 'bowler', date: '2023-11-18', year: '2023', month: '2023-11', opponent: 'Iron Invaders', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 3.4, balls: 22, runs: 33, wickets: 2, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 9.0 }, createdAt: '2023-11-18T10:00:00Z' },

  // Match 20 - Titanium Titans
  { id: 'match020_p001', matchId: 'match020', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2025-01-10', year: '2025', month: '2025-01', opponent: 'Titanium Titans', batting: { didBat: true, innings: 1, runs: 69, balls: 54, fours: 7, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 127.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-01-10T10:00:00Z' },
  { id: 'match020_p003', matchId: 'match020', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2025-01-10', year: '2025', month: '2025-01', opponent: 'Titanium Titans', batting: { didBat: true, innings: 1, runs: 82, balls: 59, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 139.0 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-01-10T10:00:00Z' },
  { id: 'match020_p006', matchId: 'match020', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2025-01-10', year: '2025', month: '2025-01', opponent: 'Titanium Titans', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 22, wickets: 4, maidens: 1, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 5.5 }, createdAt: '2025-01-10T10:00:00Z' },

  // Match 21 - Platinum Panthers
  { id: 'match021_p002', matchId: 'match021', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2025-01-18', year: '2025', month: '2025-01', opponent: 'Platinum Panthers', batting: { didBat: true, innings: 1, runs: 53, balls: 43, fours: 5, sixes: 1, dismissed: true, isDuck: false, isThirty: true, isFifty: false, isHundred: false, strikeRate: 123.3 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-01-18T10:00:00Z' },
  { id: 'match021_p004', matchId: 'match021', playerId: 'p004', playerName: 'Surya Kumar Yadav', playerRole: 'batsman', date: '2025-01-18', year: '2025', month: '2025-01', opponent: 'Platinum Panthers', batting: { didBat: true, innings: 1, runs: 69, balls: 51, fours: 7, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 135.3 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-01-18T10:00:00Z' },
  { id: 'match021_p005', matchId: 'match021', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2025-01-18', year: '2025', month: '2025-01', opponent: 'Platinum Panthers', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 30, wickets: 3, maidens: 0, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 7.5 }, createdAt: '2025-01-18T10:00:00Z' },

  // Match 22 - Gold Gazelles
  { id: 'match022_p001', matchId: 'match022', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2025-02-02', year: '2025', month: '2025-02', opponent: 'Gold Gazelles', batting: { didBat: true, innings: 1, runs: 76, balls: 54, fours: 8, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 140.7 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-02-02T10:00:00Z' },
  { id: 'match022_p003', matchId: 'match022', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2025-02-02', year: '2025', month: '2025-02', opponent: 'Gold Gazelles', batting: { didBat: true, innings: 1, runs: 63, balls: 50, fours: 6, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 126.0 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-02-02T10:00:00Z' },
  { id: 'match022_p007', matchId: 'match022', playerId: 'p007', playerName: 'Kuldeep Yadav', playerRole: 'bowler', date: '2025-02-02', year: '2025', month: '2025-02', opponent: 'Gold Gazelles', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 25, wickets: 4, maidens: 1, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 6.25 }, createdAt: '2025-02-02T10:00:00Z' },

  // Match 23 - Silver Stallions
  { id: 'match023_p002', matchId: 'match023', playerId: 'p002', playerName: 'Virat Kohli', playerRole: 'batsman', date: '2025-02-14', year: '2025', month: '2025-02', opponent: 'Silver Stallions', batting: { didBat: true, innings: 1, runs: 84, balls: 58, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 144.8 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-02-14T10:00:00Z' },
  { id: 'match023_p004', matchId: 'match023', playerId: 'p004', playerName: 'Surya Kumar Yadav', playerRole: 'batsman', date: '2025-02-14', year: '2025', month: '2025-02', opponent: 'Silver Stallions', batting: { didBat: true, innings: 1, runs: 71, balls: 52, fours: 8, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 136.5 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-02-14T10:00:00Z' },
  { id: 'match023_p006', matchId: 'match023', playerId: 'p006', playerName: 'Mohammed Siraj', playerRole: 'bowler', date: '2025-02-14', year: '2025', month: '2025-02', opponent: 'Silver Stallions', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 28, wickets: 3, maidens: 1, isThreeFer: true, isFourFer: false, isFiveFer: false, economy: 7.0 }, createdAt: '2025-02-14T10:00:00Z' },

  // Match 24 - Pearl Panthers
  { id: 'match024_p001', matchId: 'match024', playerId: 'p001', playerName: 'Rohit Sharma', playerRole: 'batsman', date: '2025-02-25', year: '2025', month: '2025-02', opponent: 'Pearl Panthers', batting: { didBat: true, innings: 1, runs: 81, balls: 58, fours: 9, sixes: 2, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 139.7 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-02-25T10:00:00Z' },
  { id: 'match024_p003', matchId: 'match024', playerId: 'p003', playerName: 'KL Rahul', playerRole: 'batsman', date: '2025-02-25', year: '2025', month: '2025-02', opponent: 'Pearl Panthers', batting: { didBat: true, innings: 1, runs: 91, balls: 65, fours: 10, sixes: 3, dismissed: true, isDuck: false, isThirty: false, isFifty: true, isHundred: false, strikeRate: 140.0 }, bowling: { didBowl: false, innings: 0, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0, isThreeFer: false, isFourFer: false, isFiveFer: false, economy: 0 }, createdAt: '2025-02-25T10:00:00Z' },
  { id: 'match024_p005', matchId: 'match024', playerId: 'p005', playerName: 'Jasprit Bumrah', playerRole: 'bowler', date: '2025-02-25', year: '2025', month: '2025-02', opponent: 'Pearl Panthers', batting: { didBat: false, innings: 0, runs: 0, balls: 0, fours: 0, sixes: 0, dismissed: false, isDuck: false, isThirty: false, isFifty: false, isHundred: false, strikeRate: 0 }, bowling: { didBowl: true, innings: 1, overs: 4, balls: 24, runs: 18, wickets: 4, maidens: 2, isThreeFer: false, isFourFer: true, isFiveFer: false, economy: 4.5 }, createdAt: '2025-02-25T10:00:00Z' },
];
